# Generated by Django 3.2.8 on 2022-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcenter',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
