# Generated by Django 3.2.8 on 2021-10-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='teacher_name',
        ),
        migrations.AddField(
            model_name='user',
            name='student_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
